name: context variable demo
on: push
jobs:
  context-demo:
   runs-on: ubuntu-latest
   steps:
     - name: use context variable 
       run: |
         echo "This workflow is triggered by ${{ github.actor }}"
         echo "This action is run by branch ${{ github.repository }}"
         echo "This is triggerd from branch ${{ github.ref_name }}"
         
       
         
