name: context variable demo
on: push
jobs:
  context-demo:
   runs-on: ubuntu-latest
   steps:
     - name: use context variable 
       run: |
         echo: "This workflow is triggered by ${{ github.actor }}"
         
