name: output demo
on: push
jobs:
  build:
    outputs:
     version: ${{ steps.job1.outputs.version }}
    runs-on: ubuntu-latest
    steps:
     - name: step one
       id: job1
       run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: deploy job
        run: echo "Deploying the job with artifact version ${{ needs.build.outputs.version }}"
